# Generated by Django 5.0 on 2024-01-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogarticle_body_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='author',
            new_name='blog',
        ),
    ]
